_BASE_: "../Base-MGN.yml"

MODEL:
  BACKBONE:
    WITH_IBN: False
    EXTRA_BN: True
  PIXEL_MEAN: [89.896, 79.200, 80.073]
  PIXEL_STD: [63.872, 64.305, 63.839]
INPUT:
  REA:
    MEAN: [0.0, 0.0, 0.0]
  DO_AUTOAUG: False
SOLVER:
  HEADS_LR_FACTOR: 1.0
  BACKBONE_BN_LR_FACTOR: 1.0
  CHECKPOINT_PERIOD: 5

DATASETS:
  NAMES: ("CMDM",)
  TESTS: ("CMDM",)
  KWARGS: ''
  ROOT: "/home/dengpanfu/data"

TEST:
  EVAL_PERIOD: 30

OUTPUT_DIR: "logs/cmdm/mgn_lup_unsup"
